# Site settings
title: Camdan's Blog
email: hello@camdan.me
author: Camdan Mead
description: "Sometimes I write about stuff and put it here."
url: "https://blog.camdan.me/"
date_format: "%b %-d, %Y"
header_pages:

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated: false
show_related_posts: false
show_about_footer: false

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data"]
permalink: pretty
paginate: 5
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
